#--------------------------------------------------------------
# Simple AWS CodeBuild Config File
#--------------------------------------------------------------
version: 0.2

name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild--${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World"